name: fish_ai
description: "AI tools for Fish!"
publish_to: 'none'
version: 0.4.0

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  # provider: ^6.1.2
  url_launcher: ^6.2.6
  package_info_plus: ^8.0.0
  shared_preferences: ^2.2.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.6.1
  flutter_markdown: ^0.7.1
  image_picker: ^1.1.2 
  google_generative_ai: ^0.4.0
  dynamic_color: ^1.8.0
  scrollable_positioned_list: ^0.3.5
  cupertino_icons: ^1.0.8
  google_mobile_ads: ^6.0.0
  firebase_core: ^4.1.0
  firebase_ai: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  macos:
    generate: true
  windows:
    generate: true
  web:
    generate: true
  image_path: "assets/AquaPi Logo.png"

flutter_native_splash:
  image: assets/AquaPi Logo.png
  color: "#d8f3ff"
  color_dark: "#2D3748"