// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM6ZbtHzwwSnqjy-MoKvpxKAbJy_jLKN0',
    appId: '1:209151214292:web:34131c532abcb50bc8b141',
    messagingSenderId: '209151214292',
    projectId: 'fishai-31d40',
    authDomain: 'fishai-31d40.firebaseapp.com',
    storageBucket: 'fishai-31d40.firebasestorage.app',
    measurementId: 'G-FV9KYN4GHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqmBqMJxOQV34fToX2B952kTEqIXxfNHY',
    appId: '1:209151214292:android:f88d075a89001fe2c8b141',
    messagingSenderId: '209151214292',
    projectId: 'fishai-31d40',
    storageBucket: 'fishai-31d40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP-E0q7ogvU10fKOquc0_tMSHvxP2n8Pg',
    appId: '1:209151214292:ios:d840afaeaa338917c8b141',
    messagingSenderId: '209151214292',
    projectId: 'fishai-31d40',
    storageBucket: 'fishai-31d40.firebasestorage.app',
    androidClientId: '209151214292-179fvt67uogjk8kpl0mno6tfciao6akm.apps.googleusercontent.com',
    iosClientId: '209151214292-vnbsrrd88h5noj9sprmfqjfbv03js2dd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fishai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP-E0q7ogvU10fKOquc0_tMSHvxP2n8Pg',
    appId: '1:209151214292:ios:d840afaeaa338917c8b141',
    messagingSenderId: '209151214292',
    projectId: 'fishai-31d40',
    storageBucket: 'fishai-31d40.firebasestorage.app',
    androidClientId: '209151214292-179fvt67uogjk8kpl0mno6tfciao6akm.apps.googleusercontent.com',
    iosClientId: '209151214292-vnbsrrd88h5noj9sprmfqjfbv03js2dd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fishai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx8tPwypAL-OYNzyO32upKc3zABmI3EJk',
    appId: '1:209151214292:web:fcbc769b81afb791c8b141',
    messagingSenderId: '209151214292',
    projectId: 'fishai-31d40',
    authDomain: 'fishai-31d40.firebaseapp.com',
    storageBucket: 'fishai-31d40.firebasestorage.app',
    measurementId: 'G-ZQ13GWHZ2S',
  );

}

