// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM6ZbtHzwwSnqjy-MoKvpxKAbJy_jLKN0',
    appId: '1:209151214292:web:de2f18efa1a32a51c8b141',
    messagingSenderId: '209151214292',
    projectId: 'fishai-31d40',
    authDomain: 'fishai-31d40.firebaseapp.com',
    storageBucket: 'fishai-31d40.firebasestorage.app',
    measurementId: 'G-FJX1MLT3LT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqmBqMJxOQV34fToX2B952kTEqIXxfNHY',
    appId: '1:209151214292:android:4ec677afabcb5ec4c8b141',
    messagingSenderId: '209151214292',
    projectId: 'fishai-31d40',
    storageBucket: 'fishai-31d40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP-E0q7ogvU10fKOquc0_tMSHvxP2n8Pg',
    appId: '1:209151214292:ios:4093b78a2616a58ac8b141',
    messagingSenderId: '209151214292',
    projectId: 'fishai-31d40',
    storageBucket: 'fishai-31d40.firebasestorage.app',
    iosBundleId: 'com.example.fishai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP-E0q7ogvU10fKOquc0_tMSHvxP2n8Pg',
    appId: '1:209151214292:ios:4093b78a2616a58ac8b141',
    messagingSenderId: '209151214292',
    projectId: 'fishai-31d40',
    storageBucket: 'fishai-31d40.firebasestorage.app',
    iosBundleId: 'com.example.fishai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM6ZbtHzwwSnqjy-MoKvpxKAbJy_jLKN0',
    appId: '1:209151214292:web:34131c532abcb50bc8b141',
    messagingSenderId: '209151214292',
    projectId: 'fishai-31d40',
    authDomain: 'fishai-31d40.firebaseapp.com',
    storageBucket: 'fishai-31d40.firebasestorage.app',
    measurementId: 'G-FV9KYN4GHE',
  );
}
